gemfile: Gemfile

PreCommit:
  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/haml-lint'

  HardTabs:
    enabled: true
    exclude:
      - 'lib/haml_lint/linter/README.md'

  RuboCop:
    enabled: true

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
    exclude:
      - 'config/forced_rubocop_config.yml'
