plugins:
  - rubocop-performance

AllCops:
  Exclude:
    - 'gemfiles/**'
  TargetRubyVersion: 3.0
  NewCops: disable
  SuggestExtensions: false

Lint/AssignmentInCondition:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/haml_lint/spec/**/*.rb'

Layout/DotPosition:
  EnforcedStyle: leading

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*'
    - 'lib/haml_lint/spec/**/*.rb'

Lint/MissingSuper:
  Enabled: false

Lint/NestedPercentLiteral:
  Exclude:
    - lib/haml_lint/linter/multiline_script.rb

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 24

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/haml_lint/spec/**/*.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/haml_lint/spec/**/*.rb'

# Prefer curly braces except for %i/%w/%W, since those return arrays.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
Naming/PredicatePrefix:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Lint/Void:
  Enabled: false
