name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  overcommit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b  # v1.318.0
        with:
          ruby-version: 4.0
          bundler-cache: true

      - name: Prepare environment
        run: |
          git config --local user.email "gh-actions@example.com"
          git config --local user.name "GitHub Actions"
          bundle exec overcommit --sign

      - name: Run pre-commit checks
        run: bundle exec overcommit --run
