name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  overcommit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74  # v1.314.0
        with:
          ruby-version: 4.0
          bundler-cache: true

      - name: Prepare environment
        run: |
          git config --local user.email "gh-actions@example.com"
          git config --local user.name "GitHub Actions"
          bundle exec overcommit --sign

      - name: Run pre-commit checks
        run: bundle exec overcommit --run
